# File purpose: Configuration for Codecov coverage reporting.
coverage:
  status:
    project:
      default:
        threshold: 0.5  # Fail if overall coverage drops >0.5%
    patch:
      default:
        target: 70%
        threshold: 0
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
