name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Lint (Black)
        run: black --check .
      - name: Lint (Ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy .
      - name: Tests + coverage
        env:
          OPENAI_API_KEY: "dummy"
        run: |
          pytest \
            --cov=src/discord_lm_bot \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=60
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          name: codecov-umbrella

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (no push)
        run: docker build -t discord-lm-app:ci-test .

  docs-build:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs deps
        run: |
          python -m pip install mkdocs-material \
                             mkdocstrings[python] \
                             mkdocs-linkcheck
      - name: Build docs
        run: mkdocs build --strict
