name: Issue Sync

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Task ID from PR title
        id: task
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          ID=$(python - <<'PY'
import os, re
m = re.search(r'([a-z0-9\-]+-\d+)', os.getenv("PR_TITLE", ""), re.I)
if m:
    print(m.group(1))
PY
          )
          echo "id=$ID" >>"$GITHUB_OUTPUT"

      - name: Ensure issue exists (create if missing)
        if: ${{ steps.task.outputs.id != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ISSUE=$(python tools/ensure_task_issue.py "${{ steps.task.outputs.id }}")
          echo "ISSUE=$ISSUE" >>"$GITHUB_OUTPUT"

      - name: Label and comment
        if: ${{ steps.task.outputs.id != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh issue edit "$ISSUE" --add-label "Task-ID,status:done"
          gh issue comment "$ISSUE" --body "Closed by ${{ github.event.pull_request.html_url }}"
