name: Issue Sync

on:
  pull_request:
    types: [closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Task ID
        id: task
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          ID=$(python - <<'PY'
import os, re
title = os.environ['PR_TITLE']
m = re.search(r"(?P<id>[a-z0-9-]+-[0-9]+)", title)
if m:
    print(m.group('id'))
PY
          )
          echo "id=$ID" >> "$GITHUB_OUTPUT"
      - name: Ensure issue exists
        if: steps.task.outputs.id
        run: |
          ISSUE=$(python tools/ensure_task_issue.py "${{ steps.task.outputs.id }}")
          echo "issue=$ISSUE" >> $GITHUB_OUTPUT
      - name: Label and comment
        if: steps.task.outputs.id
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ steps.task.outputs.issue }}/labels -X PUT -f labels='["Task-ID","status:done"]'
          gh api repos/${{ github.repository }}/issues/${{ steps.task.outputs.issue }}/comments -f body="Closed by ${{ github.event.pull_request.html_url }}"
