name: Issue Sync

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1 ▸ grab the Task ID out of the PR title
      - name: Extract Task ID from PR title
        id: extract
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        shell: bash
        run: |
          ID=$(python - <<'PY'
import os, re, sys
title = os.getenv("PR_TITLE", "")
m = re.search(r'([a-z0-9\-]+-\d+)', title, re.I)
if m:
    print(m.group(1))
PY
          )
          echo "id=$ID" >>"$GITHUB_OUTPUT"

      # 2 ▸ ensure that issue exists (create if missing) and capture number
      - name: Ensure issue exists
        if: ${{ steps.extract.outputs.id != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ISSUE=$(python tools/ensure_task_issue.py "${{ steps.extract.outputs.id }}")
          echo "issue=$ISSUE" >>"$GITHUB_OUTPUT"

      # 3 ▸ label & comment on the issue
      - name: Label and comment
        if: ${{ steps.extract.outputs.id != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh issue edit "$ISSUE" --add-label "Task-ID,status:done"
          gh issue comment "$ISSUE" --body "Closed by ${{ github.event.pull_request.html_url }}"
