name: Roadmap sync

on:
  issues:
    types: [opened, edited, labeled, unlabeled, closed]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: pip install requests
      - name: Regenerate roadmap
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python tools/update_state.py
      - name: Commit if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: PROJECT_STATE.md
          message: "ci: sync roadmap [skip ci]"
          default_author: github_actions
